version: '3.8'

services:
  quizmate-ai:
    build:
      context: .
      dockerfile: Dockerfile
    image: quizmate-ai-service
    container_name: quizmate-ai-service
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - API_HOST=0.0.0.0
      - API_PORT=8000
      - API_ENVIRONMENT=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s 